[project]
name = "RWSOS_Meuse_Calib2024"
version = "0.1.0"
description = "Snakemake managed cascading claibration chain."
authors = ["Michael O'Hanrahan <104068149+michaelohanrahan@users.noreply.github.com>"]
channels = ["conda-forge", "pip", "bioconda"]
platforms = ["win-64", "linux-64"]

[target.linux-64.dependencies]
python= ">=3.8"

[system-requirements]
linux = "4.18"

[tasks]
install-kernel = "python -m ipykernel install --user --name rnel name> --display-name rnel name>"

[pypi-dependencies]
ipykernel = ">=6.29.3,<6.30"
snakemake = { git = "https://github.com/michaelohanrahan/snakemake"}

[dependencies]
pip = "*"
matplotlib = "*"
hydromt_wflow = "0.6.*"
hydromt = ">=0.9.4,<0.10"
graphviz = "*"
jupyter = "*"
pulp = "*"
dvc = "*"
numpy = "<2.0"
cookiecutter = "*"
jinja2-time = "*"
snakemake-executor-plugin-slurm = ">=0.8.0,<0.9"
netcdf4 = ">=1.7.1,<2"
snakemake-executor-plugin-cluster-generic = ">=1.0.9,<2"
icecream = ">=2.1.3,<3"
plotly = ">=5.24.0,<6"
seaborn = ">=0.13.2,<0.14"
filelock = ">=3.16.0,<4"

[target.win-64.dependencies]
datrie = "*"
graphviz = "*"
hydromt = "*"
jupyter = "*"
matplotlib = "*"
numba = "*"
pandas = "*"
pip = "*"
python = ">=3.8"
