[project]
name = "RWSOS_Meuse_Calib2024"
version = "0.1.0"
description = "Snakemake managed cascading claibration chain."
authors = ["Michael O'Hanrahan <104068149+michaelohanrahan@users.noreply.github.com>"]
channels = ["conda-forge", "pip", "bioconda"]
platforms = ["win-64"]

[tasks]
install-kernel = "python -m ipykernel install --user --name <kernel name> --display-name <kernel name>"

[pypi-dependencies]
ipykernel = ">=6.29.3,<6.30"

[dependencies]
pip = ">=24.0,<25"
xclim = ">=0.48.2,<0.49"
matplotlib = ">=3.8.4,<3.9"
hydromt_wflow = "0.6.0.*"
hydromt = ">=0.9.4,<0.10"
graphviz = ">=2.38.0,<2.39"
jupyter = ">=1.0.0,<1.1"
python = "3.11.*"
pulp = ">=2.8.0,<2.9"
dvc = ">=2.46.0,<2.47"
cookiecutter = ">=2.6.0,<2.7"
jinja2-time = ">=0.2.0,<0.3"

[target.win-64.dependencies]
datrie = "*"
graphviz = "*"
hydromt = "*"
jupyter = "*"
matplotlib = "*"
numba = "*"
numpy = "*"
pandas = "*"
pip = "*"
python = ">=3.8"

[target.win-64.pypi-dependencies]
#hotpatched snakemake for metadata issue https://github.com/snakemake/snakemake/issues/2756
snakemake = {git = "https://github.com/michaelohanrahan/snakemake.git"}
