executor: cluster-generic
# configfile: $HOME/documents/RWSoS/RWSOS_Calibration/meuse/config/calib.yml
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
restart-times: 0
forceall: False
max-jobs-per-second: 4
max-status-checks-per-second: 1
jobs: 60
rerun-triggers: mtime

#successor to --cluster must be installed with pip snakemake-executor-plugin-cluster-generic  (1.0.9)
cluster-generic-submit-cmd:
  mkdir -p /u/ohanrah/documents/RWSoS/RWSOS_Calibration/rhine/data/0-log/{name} &&
  sbatch
    --partition={resources.partition}
    --account=hyd
    --time={resources.time}
    --get-user-env
    --qos={resources.qos}sacct
    --cpus-per-task={threads}
    --job-name={name}_{jobid}
    --output=/u/ohanrah/documents/RWSoS/RWSOS_Calibration/meuse_random/data/0-log/{name}/{jobid}.log
    
#scontrol show partition 4pcpu shows unlimited mem
default-resources:
  - partition="4pcpu"
  - qos="sbatch"
  - time="15-12:00:00"
  - mem_mb=32768 #32gb

cores: 4
local-cores: 4

group-components:
  - evaluate_L0=4
  - evaluate_L1=4
  - evaluate_L2=4
  - evaluate_L3=4
  - evaluate_L4=4
  - evaluate_L5=4
  - instate_L0=4
  - instate_L1=4
  - instate_L2=4
  - instate_L3=4
  - instate_L4=4
  - instate_L5=4
  - wflow_L0=4
  - wflow_L1=4
  - wflow_L2=4
  - wflow_L3=4
  - wflow_L4=4
  - wflow_L5=4








