## General
# Setting data for calibration
calib_recipe: "config/TEST_calib_recipe.json"
basin: "meuse"

base_dir: "/11209265-grade2023/wflow/RWSOS_Calibration"
log_dir: "data/0-log"
source_dir: "data/1-external"
inter_dir: "data/2-interim"
input_dir: "data/3-input"
output_dir: "data/4-output"       
vis_dir: "data/5-visualization"

# The bluesprint files to work with
base_config: "wflow_sbm_template.toml"
base_staticmaps: "staticmaps/staticmaps.nc"

# Which gauges (subcatchments) to calibrate over (needs matching observed data)
gauges: "Hall"

#ksathorfrac ML map model
ksathorfrac_map: "BRT_"
soilthickness_map: "SoilThickness_manual_cal"

# Settings the config file
starttime: "2005-01-01T00:00:00" 
endtime: "2018-02-22T00:00:00"
eval_starttime: "2005-09-01T00:00:00"
eval_endtime: "2018-02-22T00:00:00"
timestep: 3600
source_forcing_data: "forcing_Meuse_20050101_20180222_v2_wgs2_remapbil_semisstonn.nc"

#instate period (needs to run every time there is a new level introduced)
instate_starttime: "2005-01-01T00:00:00"
instate_endtime: "2006-12-31T23:00:00"


# Running model
wflow_cfg_name: "wflow_sbm.toml"
wflow_project_dir: "../bin/"
wflow_threads: 1

# Evaluation and finalizing per level
observed_data: "discharge_obs_HBV_combined.nc"
eval_starttime: "2005-08-01T00:00:00"
eval_endtime: "2014-07-31T00:00:00"
metrics: ["kge", "nselog_mm7q", "mae_peak_timing", "mape_peak_magnitude"]
dry_months: [6, 7, 8, 9, 10]
window: 72
weights: [0.2, 0.25, 0.3, 0.25]

# Overal finalizing
model_threads: 16

# Post processing
hydro_period_startdate: ["2007-08-01", "2011-08-01", "2016-08-01"]
hydro_period_length: [500, 500, 500]
hydro_period_unit: "D" 